/*
 * This source file was generated by the Gradle 'init' task
 */
package hmz.maharmeh;
import atlantafx.base.theme.Dracula;
import com.github.kwhat.jnativehook.GlobalScreen;
import com.github.kwhat.jnativehook.NativeHookException;
import com.github.kwhat.jnativehook.keyboard.NativeKeyEvent;
import com.github.kwhat.jnativehook.keyboard.NativeKeyListener;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.Clipboard;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.util.Duration;

import java.util.concurrent.atomic.AtomicBoolean;

public class App extends Application implements NativeKeyListener {
    private boolean cntrlPressed = false;
    private VBox list;
    private Stage stage;
    private String lastCopiedText = "";
    private AtomicBoolean coppiedFromApp = new AtomicBoolean(false);
    public static void main(String[] args) {
        launch(args);
    }


    public void start(Stage stage) throws Exception {
        Application.setUserAgentStylesheet(new Dracula().getUserAgentStylesheet());
        Platform.setImplicitExit(false);

        list = new VBox();
        list.setSpacing(10);

        AppToolBar toolbar1 = new AppToolBar(list);

        VBox root = new VBox();
        ScrollPane pane = new ScrollPane(list);
        pane.setFitToWidth(true);
        VBox.setVgrow(pane, Priority.ALWAYS);
        pane.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        pane.setVbarPolicy(ScrollPane.ScrollBarPolicy.AS_NEEDED);
        root.getChildren().addAll(toolbar1, pane);

        Scene scene = new Scene(root);
        scene.getStylesheets().add(App.class.getResource("/styles/item.css").toExternalForm());

        stage.setScene(scene);
        this.stage = stage;
        setUpStage();

        GlobalScreen.registerNativeHook();
        GlobalScreen.addNativeKeyListener(this);

        stage.show();
        startClipboardWatcher();
    }
    private void startClipboardWatcher() {
        Timeline watcher = new Timeline(new KeyFrame(Duration.seconds(1), event -> {
            Clipboard cb = Clipboard.getSystemClipboard();

            if (cb.hasString()) {
                String currentText = cb.getString();

                if(coppiedFromApp.get()) {
                    coppiedFromApp.set(false);
                    lastCopiedText = currentText;
                } else if(currentText != null && !currentText.equals(lastCopiedText)) {

                    lastCopiedText = currentText;

                    ClippedItem clippedItem = new ClippedItem(currentText, coppiedFromApp,(item) -> list.getChildren().remove(item));
                    if(!list.getChildren().contains(clippedItem)) {

                        list.getChildren().add(0,clippedItem);
                        deleteExcess();
                    }
                }
            }
        }));
        watcher.setCycleCount(Timeline.INDEFINITE);
        watcher.play();
    }
    @Override
    public void nativeKeyPressed(NativeKeyEvent event) {
        if(event.getKeyCode() == NativeKeyEvent.VC_CONTROL) {
            cntrlPressed = true;
        } else if(event.getKeyCode() == NativeKeyEvent.VC_SPACE  && cntrlPressed) {
            Platform.runLater(() -> {
                stage.show();
                stage.toFront();
            });
        } else if(event.getKeyCode() == NativeKeyEvent.VC_ESCAPE) {
            Platform.runLater(() -> {
                stage.hide();
            });
        }
    }
    public void nativeKeyReleased(NativeKeyEvent event) {
        if(event.getKeyCode() == NativeKeyEvent.VC_CONTROL) {
            cntrlPressed = false;
        }
    }

    private void setUpStage() {
        stage.setWidth(500);
        stage.setHeight(500);
        stage.initStyle(StageStyle.UTILITY);
        stage.setOnCloseRequest(event -> {
            System.out.println("User closed the window. Shutting down...");
            try {
                GlobalScreen.unregisterNativeHook(); // Stop the keyboard listener
            } catch (NativeHookException ex) {
                ex.printStackTrace();
            }
            Platform.exit();
            System.exit(0);
        });
    }
    private void deleteExcess() {
        if(list.getChildren().size() > 25) {
            list.getChildren().remove(list.getChildren().size() - 1);
        }
    }
}
